{{- range $.Values.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-{{ . }}
  namespace: "{{ $.Values.argo_namespace }}"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: infra-{{ . }}-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: "infra-{{ . }}-{{`{{name}}`}}"
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{`{{name}}`}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: "{{ $.Values.argo_namespace }}"
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        velero.io/exclude-from-backup: "true"
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      sources:
        - repoURL: "{{ $.Values.repoURL }}"
          targetRevision: 0.1.1
          helm:
            valueFiles:
              - "values-global.yaml"
              - "{{ . }}/values-env.yaml"
              - "{{ . }}/{{`{{name}}`}}/values-cluster.yaml"
          chart: infra-chart
      destination:
        namespace: default
        server: "{{`{{server}}`}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true
{{- end }}
